var MAJOR = 0;
var MINOR = 1;
var MAJOR_DIATONIC_NOTES = [0, 2, 4, 5, 7, 9, 11];
var MINOR_DIATONIC_NOTES = [0, 2, 3, 5, 7, 8, 10];
var MAX_NUM_NOTES = 8;

exports.MAJOR = MAJOR;
exports.MINOR = MINOR;
exports.MAJOR_DIATONIC_NOTES = MAJOR_DIATONIC_NOTES;
exports.MINOR_DIATONIC_NOTES = MINOR_DIATONIC_NOTES;
exports.MAX_NUM_NOTES = MAX_NUM_NOTES;
